/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import Controller.ConnectToSQLServer;
import Model.CT_SV_BKT;
import CustomModel.CustomTable_DanhSachChiTietBaiKiemTra;
import java.util.ArrayList;

import java.sql.Connection;


/**
 *
 * @author Jonan
 */
public class ChiTietBaiKiemTraForm extends javax.swing.JFrame {
    Connection connection = ConnectToSQLServer.ketNoiCSDL();
    
    String maBKT;
    
    ArrayList<CT_SV_BKT> danhSachChiTietBaiKiemTra = new ArrayList<>();
    /**
     * Creates new form ChiTietBaiKiemTraForm
     */
    public ChiTietBaiKiemTraForm() {
        initComponents();
        //loadDataTable_BangChiTietBaiKiemTra();
    }

    ChiTietBaiKiemTraForm(String maBKT) {
        initComponents();
        loadDataTable_BangChiTietBaiKiemTra(maBKT);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_ChiTietBaiKiemTra = new javax.swing.JLabel();
        jButton_CapNhat = new javax.swing.JButton();
        jButton_TroLai = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_ChiTietBaiKiemTra = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 440));
        setSize(new java.awt.Dimension(705, 440));

        jLabel_ChiTietBaiKiemTra.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel_ChiTietBaiKiemTra.setText("Chi Tiet bai kiem tra");

        jButton_CapNhat.setText("Cập nhật");
        jButton_CapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CapNhatActionPerformed(evt);
            }
        });

        jButton_TroLai.setText("Trở lại");
        jButton_TroLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TroLaiActionPerformed(evt);
            }
        });

        jTable_ChiTietBaiKiemTra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_ChiTietBaiKiemTra);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(460, 460, 460)
                        .addComponent(jButton_CapNhat)
                        .addGap(40, 40, 40)
                        .addComponent(jButton_TroLai))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(jLabel_ChiTietBaiKiemTra)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jLabel_ChiTietBaiKiemTra)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_CapNhat)
                    .addComponent(jButton_TroLai))
                .addGap(44, 44, 44))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_CapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CapNhatActionPerformed
        // TODO add your handling code here:
        int row = jTable_ChiTietBaiKiemTra.getRowCount();
        for(int i = 0; i< row; i++)
        {
            String sql = "UPDATE CT_SV_BKT SET Diem="+ (float)jTable_ChiTietBaiKiemTra.getValueAt(i, 2)
                    +"WHERE MaSV='"+ jTable_ChiTietBaiKiemTra.getValueAt(i, 0).toString() +"' AND MaBKT='"+ maBKT +"'";
            ConnectToSQLServer.thucHienLenhSQL(sql);
        
        }
    }//GEN-LAST:event_jButton_CapNhatActionPerformed
    private void jButton_TroLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TroLaiActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton_TroLaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChiTietBaiKiemTraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChiTietBaiKiemTraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChiTietBaiKiemTraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChiTietBaiKiemTraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChiTietBaiKiemTraForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_CapNhat;
    private javax.swing.JButton jButton_TroLai;
    private javax.swing.JLabel jLabel_ChiTietBaiKiemTra;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_ChiTietBaiKiemTra;
    // End of variables declaration//GEN-END:variables

//    private void loadDataTable_BangChiTietBaiKiemTra() {
//       jTable_ChiTietBaiKiemTra.setModel(new CustomTable_DanhSachChiTietBaiKiemTra(danhSachChiTietBaiKiemTra));
//    }

    private void loadDataTable_BangChiTietBaiKiemTra(String maBKT) {
        this.maBKT = maBKT;
        //lay du lieu tu database
        String query = "SELECT * "
                + "FROM dbo.[CT_SV_BKT] INNER JOIN dbo.[SINHVIEN] ON CT_SV_BKT.MaSV = SINHVIEN.MaSV  "
                + "INNER JOIN dbo.[BAIKIEMTRA] ON CT_SV_BKT.MaBKT = BAIKIEMTRA.MaBKT "
                + "WHERE BAIKIEMTRA.MaBKT='"+ maBKT +"'";
        ArrayList<CT_SV_BKT> danhSachChiTietBaiKiemTra = ConnectToSQLServer.layData_BangCT_SV_BKT(query);
        //sua tieu de bang
        String tieuDeBang = "CHI TIẾT BÀI KIỂM TRA " + maBKT;
        jLabel_ChiTietBaiKiemTra.setText(tieuDeBang);

        jTable_ChiTietBaiKiemTra.setModel(new CustomTable_DanhSachChiTietBaiKiemTra(danhSachChiTietBaiKiemTra));
    }

}
