/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ConnectToSQLServer;
import CustomModel.CustomTable_DanhSachBaiKiemTra_Diem;
import Model.CT_SV_BKT;
import Model.SinhVien;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Jonan
 */
public class MainSinhVienF extends javax.swing.JFrame {
    Connection connection = ConnectToSQLServer.ketNoiCSDL();
    String tenDangNhap;
    SinhVien sinhVien = new SinhVien();
    
    ArrayList<SinhVien> danhSachSinhVien = new ArrayList<>();
    ArrayList<CT_SV_BKT> danhSachChiTietBaiKiemTra = new ArrayList<>();
    int dongChon_ChiTietBaiKiemTra = -1;
    /**
     * Creates new form MainSinhVienF
     */
    public MainSinhVienF() {
        initComponents();
    }
    
    public MainSinhVienF(String tenDangNhap) {
        initComponents();
        this.tenDangNhap = tenDangNhap;
        layThongTinSinhVien();
        layBangDanhSachChiTietBaiKiemTra();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_TenSinhVien = new javax.swing.JLabel();
        jLabel_MaSinhVien = new javax.swing.JLabel();
        jLabel_MaLop = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_DanhSachChiTietBaiKiemTra = new javax.swing.JTable();
        jButton_LamBai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(705, 440));
        setResizable(false);
        setSize(new java.awt.Dimension(705, 440));

        jLabel_TenSinhVien.setText("Ten sinh vien");

        jLabel_MaSinhVien.setText("ma sinh vien");

        jLabel_MaLop.setText("ma lop");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("DANH SÁCH BÀI KIỂM TRA");

        jTable_DanhSachChiTietBaiKiemTra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_DanhSachChiTietBaiKiemTra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_DanhSachChiTietBaiKiemTraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_DanhSachChiTietBaiKiemTra);

        jButton_LamBai.setText("Làm bài");
        jButton_LamBai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LamBaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel_MaSinhVien)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel_TenSinhVien)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel_MaLop)
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(251, 251, 251))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton_LamBai)
                        .addGap(126, 126, 126))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_TenSinhVien)
                    .addComponent(jLabel_MaSinhVien)
                    .addComponent(jLabel_MaLop))
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton_LamBai)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable_DanhSachChiTietBaiKiemTraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_DanhSachChiTietBaiKiemTraMouseClicked
        // TODO add your handling code here:
        dongChon_ChiTietBaiKiemTra = jTable_DanhSachChiTietBaiKiemTra.rowAtPoint(evt.getPoint());
    }//GEN-LAST:event_jTable_DanhSachChiTietBaiKiemTraMouseClicked

    private void jButton_LamBaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LamBaiActionPerformed
        // TODO add your handling code here:
        String trangThai = danhSachChiTietBaiKiemTra.get(dongChon_ChiTietBaiKiemTra).getTrangThai();
        if(trangThai.equals("Hoàn thành"))
        {
            JOptionPane.showMessageDialog(null, "Bạn đã làm bài kiểm tra này rồi");
        }
        else{
            new LamBaiKiemTra(danhSachChiTietBaiKiemTra.get(dongChon_ChiTietBaiKiemTra).getBaiKiemTra().getMaBKT()
                    , sinhVien.getMaSV()).setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton_LamBaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainSinhVienF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainSinhVienF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainSinhVienF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainSinhVienF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainSinhVienF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_LamBai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_MaLop;
    private javax.swing.JLabel jLabel_MaSinhVien;
    private javax.swing.JLabel jLabel_TenSinhVien;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_DanhSachChiTietBaiKiemTra;
    // End of variables declaration//GEN-END:variables

    private void layThongTinSinhVien() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        String sql = "SELECT * FROM SINHVIEN "
                + "INNER JOIN LOP ON SINHVIEN.MaLop = LOP.MaLop "
                + "WHERE TenDangNhap='" +tenDangNhap+ "'";
        danhSachSinhVien = ConnectToSQLServer.layData_BangSinhVien(sql);
        
        sinhVien = danhSachSinhVien.get(0);
        jLabel_MaSinhVien.setText(sinhVien.getMaSV());
        jLabel_TenSinhVien.setText(sinhVien.getTenSV());
        jLabel_MaLop.setText(sinhVien.getLop().getMaLop());
    }

    private void layBangDanhSachChiTietBaiKiemTra() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        String sql = "SELECT * FROM dbo.[CT_SV_BKT] INNER JOIN dbo.[SINHVIEN] ON CT_SV_BKT.MaSV = SINHVIEN.MaSV  "
                + "INNER JOIN dbo.[BAIKIEMTRA] ON CT_SV_BKT.MaBKT = BAIKIEMTRA.MaBKT "
                + "WHERE BAIKIEMTRA.MaLop='"+ sinhVien.getLop().getMaLop() +"'";
        danhSachChiTietBaiKiemTra = ConnectToSQLServer.layData_BangCT_SV_BKT(sql);
        
        jTable_DanhSachChiTietBaiKiemTra.setModel(new CustomTable_DanhSachBaiKiemTra_Diem(danhSachChiTietBaiKiemTra));
    }
}
