/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ConnectToSQLServer;
import Model.BaiKiemTra;
import CustomModel.CustomTable_DanhSachBaiKiemTra;
import CustomModel.CustomTable_DanhSachLop;
import Model.GiangVien;
import Model.Lop;
import java.sql.Connection;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;


/**
 *
 * @author Jonan
 */
public class MainMenuGiangVien extends javax.swing.JFrame {
    Connection connection = ConnectToSQLServer.ketNoiCSDL();
    String tenDangNhap = new String();
    ArrayList<Lop> danhSachLop = new ArrayList<>();
    int dongChon_Lop = -1;
    ArrayList<BaiKiemTra> danhSachBaiKiemTra = new ArrayList<>();
    int dongChon_BaiKiemTra = -1;

    /**
     * Creates new form MainMenuGiangVien
     */
    public MainMenuGiangVien() {
        initComponents();
//        this.setLocationRelativeTo(null);  // *** this will center your app ***

        loadDataTable_BangDanhSachLop();
        loadDataTable_BangDanhSachBaiKiemTra();
    }

    public MainMenuGiangVien(String tenDN) {
        initComponents();
        tenDangNhap = tenDN;
        
        loadDataTable_BangDanhSachLop();
        loadDataTable_BangDanhSachBaiKiemTra();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_QuanLyBaiKiemTra = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_DanhSachBaiKiemTra = new javax.swing.JTable();
        btnTao = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        JButton_XoaBaiKiemTra = new javax.swing.JButton();
        jPanel_QuanLyLop = new javax.swing.JPanel();
        jLabel_DanhSachLop = new javax.swing.JLabel();
        jButton_XoaLop = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_DanhSachLop = new javax.swing.JTable();
        jButton_TaoLop = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 420));
        setResizable(false);
        setSize(new java.awt.Dimension(705, 440));

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("QUẢN LÍ BÀI KIỂM TRA");

        jTable_DanhSachBaiKiemTra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_DanhSachBaiKiemTra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_DanhSachBaiKiemTraMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_DanhSachBaiKiemTra);

        btnTao.setText("Tạo ");
        btnTao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        JButton_XoaBaiKiemTra.setText("Xóa");
        JButton_XoaBaiKiemTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_XoaBaiKiemTraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_QuanLyBaiKiemTraLayout = new javax.swing.GroupLayout(jPanel_QuanLyBaiKiemTra);
        jPanel_QuanLyBaiKiemTra.setLayout(jPanel_QuanLyBaiKiemTraLayout);
        jPanel_QuanLyBaiKiemTraLayout.setHorizontalGroup(
            jPanel_QuanLyBaiKiemTraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_QuanLyBaiKiemTraLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(btnTao, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164)
                .addComponent(JButton_XoaBaiKiemTra, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
            .addGroup(jPanel_QuanLyBaiKiemTraLayout.createSequentialGroup()
                .addGroup(jPanel_QuanLyBaiKiemTraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_QuanLyBaiKiemTraLayout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_QuanLyBaiKiemTraLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_QuanLyBaiKiemTraLayout.setVerticalGroup(
            jPanel_QuanLyBaiKiemTraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_QuanLyBaiKiemTraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(jPanel_QuanLyBaiKiemTraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTao)
                    .addComponent(btnSua)
                    .addComponent(JButton_XoaBaiKiemTra))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Quản lý bài kiểm tra", jPanel_QuanLyBaiKiemTra);

        jLabel_DanhSachLop.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel_DanhSachLop.setText("DANH SÁCH LỚP");

        jButton_XoaLop.setText("Xoá");
        jButton_XoaLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_XoaLopActionPerformed(evt);
            }
        });

        jTable_DanhSachLop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_DanhSachLop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_DanhSachLopMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable_DanhSachLop);

        jButton_TaoLop.setText("Tạo");
        jButton_TaoLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TaoLopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_QuanLyLopLayout = new javax.swing.GroupLayout(jPanel_QuanLyLop);
        jPanel_QuanLyLop.setLayout(jPanel_QuanLyLopLayout);
        jPanel_QuanLyLopLayout.setHorizontalGroup(
            jPanel_QuanLyLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_QuanLyLopLayout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addGroup(jPanel_QuanLyLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_QuanLyLopLayout.createSequentialGroup()
                        .addComponent(jLabel_DanhSachLop)
                        .addGap(289, 289, 289))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_QuanLyLopLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_QuanLyLopLayout.createSequentialGroup()
                        .addComponent(jButton_TaoLop)
                        .addGap(132, 132, 132)
                        .addComponent(jButton_XoaLop)
                        .addGap(206, 206, 206))))
        );
        jPanel_QuanLyLopLayout.setVerticalGroup(
            jPanel_QuanLyLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_QuanLyLopLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel_DanhSachLop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_QuanLyLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_TaoLop)
                    .addComponent(jButton_XoaLop))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Quản lý lớp", jPanel_QuanLyLop);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_XoaLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_XoaLopActionPerformed
        // TODO add your handling code here:
        if(dongChon_Lop < 0)
        {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn dòng nào để xóa", "Thông báo", JOptionPane.DEFAULT_OPTION);
            return;
        }
        
        Object[] options = { "Có", "Không" };
        //Check = 0: co 1: khong
        int check = JOptionPane.showOptionDialog(null, "Bạn chắc chắn muốn xóa ?", "Thông Báo",
                                    JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE,
                                    null, options, options[0]);
        
        if(check == 0)
        {
            String maLop = jTable_DanhSachLop.getValueAt(dongChon_Lop, 0).toString();
            String query = "DELETE dbo.[LOP] WHERE MaLop= '"+maLop+"'";
            ConnectToSQLServer.thucHienLenhSQL(query);
            
            dongChon_Lop = -1;
            loadDataTable_BangDanhSachLop();
        }   
    }//GEN-LAST:event_jButton_XoaLopActionPerformed

    private void JButton_XoaBaiKiemTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_XoaBaiKiemTraActionPerformed
        // TODO add your handling code here:
        if(dongChon_BaiKiemTra < 0)
        {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn dòng nào để xóa", "Thông báo", JOptionPane.DEFAULT_OPTION);
            return;
        }
        
        Object[] options = { "Có", "Không" };
        //Check = 0: co 1: khong
        int check = JOptionPane.showOptionDialog(null, "Bạn chắc chắn muốn xóa ?", "Thông Báo",
                                    JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE,
                                    null, options, options[0]);
        
        if(check == 0)
        {
            String maBKT = jTable_DanhSachBaiKiemTra.getValueAt(dongChon_BaiKiemTra, 0).toString();
            String query = "DELETE dbo.[BaiKiemTra] WHERE MaBKT= '"+maBKT+"'";
            ConnectToSQLServer.thucHienLenhSQL(query);
            
            dongChon_Lop = -1;
            loadDataTable_BangDanhSachBaiKiemTra();
        }   
    }//GEN-LAST:event_JButton_XoaBaiKiemTraActionPerformed

    private void jTable_DanhSachBaiKiemTraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_DanhSachBaiKiemTraMouseClicked
        // TODO add your handling code here:
        dongChon_BaiKiemTra = jTable_DanhSachBaiKiemTra.rowAtPoint(evt.getPoint());
    }//GEN-LAST:event_jTable_DanhSachBaiKiemTraMouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
        loadDataTable_BangDanhSachBaiKiemTra();
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jTable_DanhSachLopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_DanhSachLopMouseClicked
        // TODO add your handling code here:
        dongChon_Lop= jTable_DanhSachLop.rowAtPoint(evt.getPoint());
        if (evt.getClickCount() == 2 && evt.getButton() == MouseEvent.BUTTON1) {
            new DanhSachBaiKiemTraForm(danhSachLop.get(dongChon_Lop).getMaLop()).setVisible(true);
        }
    }//GEN-LAST:event_jTable_DanhSachLopMouseClicked

    private void btnTaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoActionPerformed
        // TODO add your handling code here:
       new GDTaoBKT().setVisible(true);
    }//GEN-LAST:event_btnTaoActionPerformed

    private void jButton_TaoLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TaoLopActionPerformed
        // TODO add your handling code here:
        String sql = "SELECT * FROM GIANGVIEN INNER JOIN TAIKHOAN ON GIANGVIEN.TenDangNhap = TAIKHOAN.TenDangNhap";
        ArrayList<GiangVien> temp = ConnectToSQLServer.layData_BangGiangVien(sql);
            
        new TaoLop(temp.get(0).getMaGV()).setVisible(true);
    }//GEN-LAST:event_jButton_TaoLopActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        String maBKT = danhSachBaiKiemTra.get(dongChon_BaiKiemTra).getMaBKT();
        new SuaBaiKiemTraF(maBKT).setVisible(true);
    }//GEN-LAST:event_btnSuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuGiangVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuGiangVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuGiangVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuGiangVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuGiangVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButton_XoaBaiKiemTra;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnTao;
    private javax.swing.JButton jButton_TaoLop;
    private javax.swing.JButton jButton_XoaLop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_DanhSachLop;
    private javax.swing.JPanel jPanel_QuanLyBaiKiemTra;
    private javax.swing.JPanel jPanel_QuanLyLop;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable_DanhSachBaiKiemTra;
    private javax.swing.JTable jTable_DanhSachLop;
    // End of variables declaration//GEN-END:variables

    private void loadDataTable_BangDanhSachLop() {
        danhSachLop.clear();
        //lay du lieu tu database
        String query = "SELECT * FROM Lop INNER JOIN GIANGVIEN ON Lop.MaGV = GIANGVIEN.MaGV "
                + "WHERE TenDangNhap = '"+ tenDangNhap +"'";
        danhSachLop = ConnectToSQLServer.layData_BangLop(query);

        jTable_DanhSachLop.setModel(new CustomTable_DanhSachLop(danhSachLop));
    }

    private void loadDataTable_BangDanhSachBaiKiemTra() {
        danhSachBaiKiemTra.clear(); 
        //lay du lieu tu database
        Iterator<Lop> it = danhSachLop.iterator();
        while(it.hasNext())
        {
            String query = "SELECT * FROM dbo.[BAIKIEMTRA] INNER JOIN dbo.[LOP] ON BAIKIEMTRA.MaLop = LOP.MaLop "
                    + "WHERE BaiKiemTra.MaLop = '" + it.next().getMaLop() + "'";
            ArrayList<BaiKiemTra> temp = ConnectToSQLServer.layData_BangBaiKiemTra(query);
            danhSachBaiKiemTra.addAll(temp);
        }

        jTable_DanhSachBaiKiemTra.setModel(new CustomTable_DanhSachBaiKiemTra(danhSachBaiKiemTra));
    }
}
